name: ${project.name}
version: ${project.version}
description: ${project.description}
main: ovh.excale.mc.UHC
authors:
  - Excale
  - Cr4zy5ky_U
  - dev_excale@hotmail.com
depend:
  - CommandAPI
api-version: "1.13"
website: http://mc.excale.ovh/
load: POSTWORLD