debug: true
uhc:
  border:
    InitialSize: 600
    actions:

      # - Size: 1600       ; Border size
      #   Timestamp: 120   ; Game timestamp (minutes)
      #   ShrinkTime: 12   ; Shrink time (seconds)

      - BorderSize: 500
        Minutes: 1
        Action: Shrink

      - Minutes: 1
        Action: Hold

      - BorderSize: 200
        Minutes: 1
        Action: Shrink

      - Minutes: 1
        Action: Hold

      - BorderSize: 20
        Minutes: 1
        Action: Shrink
